services:
  frontend:
    build:
      context: .
      dockerfile: apps/sign/Dockerfile
    container_name: sign-frontend
    ports:
      - '5173:5173'
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/sign/node_modules

  managex:
    build:
      context: .
      dockerfile: apps/managex/Dockerfile
    container_name: sign-managex
    ports:
      - '5175:5175'
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/managex/node_modules
