-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create custom ENUM types
DO $$ BEGIN
  CREATE TYPE user_role AS ENUM (
    'SYSTEM_ADMIN', 'OPERATIONS', 'OWNER_ADMIN', 'OWNER_CREATOR',
    'OWNER_REVIEWER', 'CONTRACTOR_ADMIN', 'CONTRACTOR_CREATOR',
    'CONTRACTOR_REVIEWER', 'CONTRACTOR_TENDERING'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE contract_status AS ENUM (
    'DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'PENDING_TENDERING',
    'SENT_TO_CONTRACTOR', 'CONTRACTOR_REVIEWING', 'PENDING_FINAL_APPROVAL',
    'CHANGES_REQUESTED', 'RISK_ESCALATION_PENDING', 'ACTIVE', 'COMPLETED', 'TERMINATED'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE risk_level AS ENUM ('LOW', 'MEDIUM', 'HIGH');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE asset_type AS ENUM (
    'LAW', 'INTERNATIONAL_STANDARD', 'ORGANIZATION_POLICY', 'CONTRACT_TEMPLATE', 'KNOWLEDGE'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE asset_review_status AS ENUM (
    'PENDING_REVIEW', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'AUTO_APPROVED'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE subscription_status AS ENUM ('ACTIVE', 'INACTIVE', 'CANCELLED', 'EXPIRED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE obligation_status AS ENUM ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE notification_type AS ENUM ('EMAIL', 'IN_APP', 'BOTH');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
