import { Injectable, Logger } from '@nestjs/common';
import {
  ComplianceCheck,
  ComplianceFinding,
  ComplianceFindingLayer,
  ComplianceFindingSeverity,
  Contract,
  Obligation,
  ObligationStatus,
  Project,
  Organization,
  User,
} from '../../../database/entities';
import * as crypto from 'crypto';

// pdfmake types are loose — we use `any` like the existing ExportService.
type DocDef = any;

const BRAND = {
  primary: '#4F6EF7',
  dark: '#0F1729',
  muted: '#6B7280',
  light: '#F8FAFF',
  red: '#DC2626',
  amber: '#D97706',
  green: '#059669',
};

export interface ReportContext {
  contract: Contract;
  project: Project;
  organization: Organization | null;
  user: User;
  generatedAt: Date;
  jurisdiction: string | null;
}

/**
 * Generates the 3 SIGN compliance reports as Buffer-encoded PDFs.
 *
 * All reports follow the Global Report Standards:
 *   - SIGN diagonal watermark on every page
 *   - Confidentiality footer with page numbers
 *   - Cover page with SIGN branding, contract / project / org metadata
 *   - PDF permissions: print=allowed, edit/copy=denied (random owner pwd)
 */
@Injectable()
export class PdfReportService {
  private readonly logger = new Logger(PdfReportService.name);

  // ─── Public entry points ─────────────────────────────────

  async buildComplianceSummary(input: {
    ctx: ReportContext;
    check: ComplianceCheck;
    findings: ComplianceFinding[];
  }): Promise<Buffer> {
    const docDef = this.commonDoc(input.ctx, 'Compliance Summary Report');
    docDef.content.push(...this.summarySection(input.check, input.findings));
    docDef.content.push({ text: '', pageBreak: 'before' });
    docDef.content.push(...this.findingsByLayerSection(input.findings));
    return this.toBuffer(docDef);
  }

  async buildJurisdictionConflict(input: {
    ctx: ReportContext;
    check: ComplianceCheck;
    findings: ComplianceFinding[];
  }): Promise<Buffer> {
    const docDef = this.commonDoc(input.ctx, 'Jurisdiction Conflict Report');
    const conflictFindings = input.findings.filter(
      (f) =>
        f.layer === ComplianceFindingLayer.JURISDICTION ||
        f.layer === ComplianceFindingLayer.CONFLICT,
    );
    docDef.content.push(...this.jurisdictionExecSummary(input.check, conflictFindings));
    docDef.content.push({ text: '', pageBreak: 'before' });
    docDef.content.push(...this.conflictAnalysisTable(conflictFindings));
    docDef.content.push(...this.missingLawSection(conflictFindings));
    docDef.content.push(...this.governingLawSection(input.ctx));
    docDef.content.push(...this.recommendedAmendmentsSection(conflictFindings));
    return this.toBuffer(docDef);
  }

  async buildObligationsReport(input: {
    ctx: ReportContext;
    check?: ComplianceCheck;
    obligations: Obligation[];
  }): Promise<Buffer> {
    const docDef = this.commonDoc(input.ctx, 'Critical Obligations Report');
    docDef.content.push(...this.obligationsExecSummary(input.obligations));
    docDef.content.push({ text: '', pageBreak: 'before' });
    docDef.content.push(...this.obligationsTablesByParty(input.obligations));
    docDef.content.push({ text: '', pageBreak: 'before' });
    docDef.content.push(...this.criticalDatesTimeline(input.obligations));
    docDef.content.push(...this.timeframesReferenceTable(input.obligations));
    return this.toBuffer(docDef);
  }

  // ─── Common doc skeleton ──────────────────────────────────

  private commonDoc(ctx: ReportContext, title: string): DocDef {
    const date = ctx.generatedAt.toUTCString();
    const orgName = ctx.organization?.name ?? '—';
    const userName = `${ctx.user.first_name ?? ''} ${ctx.user.last_name ?? ''}`.trim() || ctx.user.email;
    const cover: any[] = [
      {
        margin: [0, 80, 0, 0],
        text: 'SIGN',
        fontSize: 36,
        bold: true,
        color: BRAND.primary,
        alignment: 'center',
      },
      {
        margin: [0, 4, 0, 60],
        text: 'Contract & Legal Intelligence',
        fontSize: 11,
        color: BRAND.muted,
        alignment: 'center',
      },
      {
        text: title,
        fontSize: 26,
        bold: true,
        color: BRAND.dark,
        alignment: 'center',
        margin: [0, 0, 0, 40],
      },
      {
        margin: [60, 0, 60, 0],
        layout: 'noBorders',
        table: {
          widths: ['*', '*'],
          body: [
            [coverLabel('Contract'), coverValue(ctx.contract.name)],
            [coverLabel('Project'), coverValue(ctx.project.name)],
            [coverLabel('Organization'), coverValue(orgName)],
            [coverLabel('Jurisdiction'), coverValue(ctx.jurisdiction ?? '—')],
            [coverLabel('Generated'), coverValue(date)],
            [coverLabel('Generated by'), coverValue(userName)],
          ],
        },
      },
      { text: '', pageBreak: 'after' },
    ];

    return {
      content: cover,
      pageSize: 'A4',
      pageMargins: [50, 60, 50, 80] as [number, number, number, number],
      defaultStyle: { font: 'Helvetica', fontSize: 10, color: BRAND.dark },
      header: () => null,
      // Diagonal SIGN watermark every page
      background: (currentPage: number, pageSize: any) => ({
        canvas: this.watermarkCanvas(pageSize.width, pageSize.height),
      }),
      // Confidentiality footer + page number
      footer: (currentPage: number, pageCount: number) => ({
        margin: [50, 20, 50, 20],
        columns: [
          {
            text:
              'This document is confidential and intended solely for the addressee. ' +
              `Generated by SIGN Platform on ${date}. Unauthorized distribution is prohibited.`,
            fontSize: 7,
            color: BRAND.muted,
            italics: true,
            width: '*',
          },
          {
            text: `Page ${currentPage} of ${pageCount}`,
            fontSize: 8,
            color: BRAND.muted,
            alignment: 'right',
            width: 80,
          },
        ],
      }),
      info: {
        title,
        author: 'SIGN Platform',
        subject: title,
        creator: 'SIGN Platform',
        producer: 'SIGN Platform',
      },
    };
  }

  // ─── Summary report sections ──────────────────────────────

  private summarySection(
    check: ComplianceCheck,
    findings: ComplianceFinding[],
  ): any[] {
    const total = findings.length;
    const critical = findings.filter(
      (f) => f.severity === ComplianceFindingSeverity.CRITICAL,
    ).length;
    const high = findings.filter(
      (f) => f.severity === ComplianceFindingSeverity.HIGH,
    ).length;

    const statusColor =
      check.overall_status === 'COMPLIANT'
        ? BRAND.green
        : check.overall_status === 'NON_COMPLIANT'
        ? BRAND.red
        : BRAND.amber;

    return [
      sectionHeading('1. Executive Summary'),
      paragraph(
        `Standard checked: ${check.contract_type ?? '—'}. ` +
          `Jurisdiction: ${check.jurisdiction ?? '—'}.`,
      ),
      paragraph(`Knowledge sources used: ${check.knowledge_assets_used?.length ?? 0}.`),
      {
        margin: [0, 12, 0, 12],
        layout: 'noBorders',
        table: {
          widths: ['*', '*', '*'],
          body: [
            [
              statBlock('Overall Status', check.overall_status, statusColor),
              statBlock('Total Findings', String(total), BRAND.dark),
              statBlock('Critical', String(critical), BRAND.red),
            ],
          ],
        },
      },
      paragraph(`High-severity findings: ${high}`),
    ];
  }

  private findingsByLayerSection(findings: ComplianceFinding[]): any[] {
    const layers: ComplianceFindingLayer[] = [
      ComplianceFindingLayer.STANDARD,
      ComplianceFindingLayer.JURISDICTION,
      ComplianceFindingLayer.PLAYBOOK,
      ComplianceFindingLayer.CONFLICT,
    ];
    const out: any[] = [sectionHeading('2. Findings by Layer')];
    for (const layer of layers) {
      const subset = findings.filter((f) => f.layer === layer);
      if (subset.length === 0) continue;
      out.push({
        margin: [0, 14, 0, 6],
        text: layerTitle(layer),
        bold: true,
        fontSize: 13,
        color: BRAND.primary,
      });
      out.push(this.findingsTable(subset));
    }
    return out;
  }

  private findingsTable(findings: ComplianceFinding[]): any {
    return {
      margin: [0, 4, 0, 12],
      layout: 'lightHorizontalLines',
      table: {
        headerRows: 1,
        widths: [50, '*', 60, 'auto'],
        body: [
          [
            { text: 'Clause', style: 'th' },
            { text: 'Requirement / Recommendation', style: 'th' },
            { text: 'Severity', style: 'th' },
            { text: 'Status', style: 'th' },
          ],
          ...findings.map((f) => [
            { text: f.clause_ref ?? '—', fontSize: 8 },
            {
              stack: [
                { text: f.requirement, fontSize: 9 },
                f.recommendation
                  ? {
                      text: `→ ${f.recommendation}`,
                      fontSize: 8,
                      italics: true,
                      color: BRAND.muted,
                      margin: [0, 2, 0, 0],
                    }
                  : null,
              ].filter(Boolean),
            },
            severityCell(f.severity),
            { text: f.status, fontSize: 8 },
          ]),
        ],
      },
      styles: { th: { bold: true, fontSize: 9, color: BRAND.muted } },
    };
  }

  // ─── Jurisdiction Conflict sections ───────────────────────

  private jurisdictionExecSummary(
    check: ComplianceCheck,
    findings: ComplianceFinding[],
  ): any[] {
    const critical = findings.filter(
      (f) => f.severity === ComplianceFindingSeverity.CRITICAL,
    ).length;
    return [
      sectionHeading('1. Executive Summary'),
      paragraph(`Jurisdiction checked: ${check.jurisdiction ?? '—'}`),
      paragraph(`Contract standard: ${check.contract_type ?? '—'}`),
      paragraph(`Total conflicts identified: ${findings.length}`),
      paragraph(
        `Critical conflicts (where local law overrides FIDIC/NEC): ${critical}`,
      ),
    ];
  }

  private conflictAnalysisTable(findings: ComplianceFinding[]): any[] {
    return [
      sectionHeading('2. Conflict Analysis'),
      {
        margin: [0, 4, 0, 12],
        layout: 'lightHorizontalLines',
        table: {
          headerRows: 1,
          widths: [60, '*', '*', 60],
          body: [
            [
              { text: 'Standard Clause', style: 'th' },
              { text: 'Standard Provision', style: 'th' },
              { text: 'Local Law / Recommendation', style: 'th' },
              { text: 'Severity', style: 'th' },
            ],
            ...findings.map((f) => [
              { text: f.clause_ref ?? '—', fontSize: 8 },
              { text: f.requirement, fontSize: 9 },
              { text: f.recommendation ?? '—', fontSize: 9 },
              severityCell(f.severity),
            ]),
          ],
        },
      },
    ];
  }

  private missingLawSection(findings: ComplianceFinding[]): any[] {
    const missing = findings.filter(
      (f) => f.finding_type === 'MISSING_CLAUSE',
    );
    if (missing.length === 0) return [];
    return [
      sectionHeading('3. Missing Local Law Requirements'),
      ...missing.map((f) =>
        bulletPara(`${f.clause_ref ? `[${f.clause_ref}] ` : ''}${f.requirement}`),
      ),
    ];
  }

  private governingLawSection(ctx: ReportContext): any[] {
    return [
      sectionHeading('4. Governing Law Analysis'),
      paragraph(
        `The contract for "${ctx.contract.name}" is associated with jurisdiction ` +
          `"${ctx.jurisdiction ?? '—'}". Disputes are subject to the dispute-resolution ` +
          `mechanism specified in the contract; review the conflicts above to ensure ` +
          `enforceability under local law.`,
      ),
    ];
  }

  private recommendedAmendmentsSection(findings: ComplianceFinding[]): any[] {
    const recs = findings.filter((f) => f.recommendation);
    if (recs.length === 0) return [];
    return [
      sectionHeading('5. Recommended Particular Conditions'),
      ...recs.map((f) =>
        bulletPara(`${f.clause_ref ? `[${f.clause_ref}] ` : ''}${f.recommendation}`),
      ),
    ];
  }

  // ─── Obligations report sections ──────────────────────────

  private obligationsExecSummary(obligations: Obligation[]): any[] {
    const total = obligations.length;
    const critical = obligations.filter((o) => o.is_critical).length;
    const overdue = obligations.filter(
      (o) => o.status === ObligationStatus.OVERDUE,
    ).length;
    const byParty = (party: string) =>
      obligations.filter((o) => o.responsible_party === party).length;

    const upcoming = obligations
      .filter(
        (o) =>
          o.due_date &&
          o.status !== ObligationStatus.MET &&
          o.status !== ObligationStatus.COMPLETED,
      )
      .sort((a, b) => +new Date(a.due_date) - +new Date(b.due_date))[0];

    return [
      sectionHeading('1. Executive Summary'),
      paragraph(`Total obligations identified: ${total}`),
      paragraph(`Critical obligations: ${critical}`),
      paragraph(
        `By party — Contractor: ${byParty('CONTRACTOR')} · ` +
          `Employer: ${byParty('EMPLOYER')} · ` +
          `Engineer: ${byParty('ENGINEER')}`,
      ),
      paragraph(`Overdue obligations: ${overdue}`),
      upcoming
        ? paragraph(
            `Nearest upcoming deadline: ${new Date(
              upcoming.due_date,
            ).toDateString()} — ${upcoming.description.slice(0, 100)}`,
          )
        : paragraph('No upcoming fixed-date obligations.'),
    ];
  }

  private obligationsTablesByParty(obligations: Obligation[]): any[] {
    const parties: Array<['CONTRACTOR' | 'EMPLOYER' | 'ENGINEER', string]> = [
      ['CONTRACTOR', '2. Contractor Obligations'],
      ['EMPLOYER', '3. Employer Obligations'],
      ['ENGINEER', '4. Engineer Obligations'],
    ];
    const out: any[] = [];
    for (const [party, heading] of parties) {
      const rows = obligations
        .filter((o) => o.responsible_party === party)
        .sort((a, b) =>
          a.due_date && b.due_date
            ? +new Date(a.due_date) - +new Date(b.due_date)
            : 0,
        );
      out.push(sectionHeading(heading));
      if (rows.length === 0) {
        out.push(paragraph('— None —'));
        continue;
      }
      out.push(this.obligationsTable(rows));
    }
    return out;
  }

  private obligationsTable(rows: Obligation[]): any {
    return {
      margin: [0, 4, 0, 12],
      layout: 'lightHorizontalLines',
      table: {
        headerRows: 1,
        widths: [40, '*', 70, 60, 50, 50, 40],
        body: [
          [
            { text: 'Clause', style: 'th' },
            { text: 'Description', style: 'th' },
            { text: 'Timeframe', style: 'th' },
            { text: 'Due', style: 'th' },
            { text: 'Amount', style: 'th' },
            { text: 'Status', style: 'th' },
            { text: 'Crit?', style: 'th' },
          ],
          ...rows.map((o) => [
            { text: o.clause_ref ?? '—', fontSize: 8 },
            {
              text: o.description,
              fontSize: 8,
              color: o.is_critical ? BRAND.red : BRAND.dark,
            },
            { text: o.timeframe_description ?? o.duration ?? '—', fontSize: 8 },
            {
              text: o.due_date ? new Date(o.due_date).toDateString() : '—',
              fontSize: 8,
            },
            {
              text: o.amount ? `${o.amount} ${o.currency ?? ''}` : '—',
              fontSize: 8,
            },
            { text: statusLabel(o.status), fontSize: 8 },
            { text: o.is_critical ? 'YES' : '—', fontSize: 8 },
          ]),
        ],
      },
      styles: { th: { bold: true, fontSize: 8, color: BRAND.muted } },
    };
  }

  private criticalDatesTimeline(obligations: Obligation[]): any[] {
    const dated = obligations
      .filter((o) => o.due_date)
      .sort((a, b) => +new Date(a.due_date) - +new Date(b.due_date));
    if (dated.length === 0) return [];
    return [
      sectionHeading('5. Critical Dates Timeline'),
      ...dated.map((o) =>
        bulletPara(
          `${new Date(o.due_date).toDateString()} — ` +
            `${o.is_critical ? '[CRITICAL] ' : ''}` +
            `${o.description.slice(0, 140)}`,
        ),
      ),
    ];
  }

  private timeframesReferenceTable(obligations: Obligation[]): any[] {
    const withDuration = obligations.filter(
      (o) => o.duration || o.timeframe_description,
    );
    if (withDuration.length === 0) return [];
    return [
      sectionHeading('6. Contractual Timeframes Reference'),
      {
        margin: [0, 4, 0, 12],
        layout: 'lightHorizontalLines',
        table: {
          headerRows: 1,
          widths: [50, 80, '*'],
          body: [
            [
              { text: 'Clause', style: 'th' },
              { text: 'Period', style: 'th' },
              { text: 'Description', style: 'th' },
            ],
            ...withDuration.map((o) => [
              { text: o.clause_ref ?? '—', fontSize: 8 },
              {
                text: o.duration ?? o.timeframe_description ?? '—',
                fontSize: 8,
              },
              { text: o.description, fontSize: 8 },
            ]),
          ],
        },
        styles: { th: { bold: true, fontSize: 9, color: BRAND.muted } },
      },
    ];
  }

  // ─── PDF rendering ────────────────────────────────────────

  private toBuffer(docDef: DocDef): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const PdfPrinter = require('pdfmake');
        const printer = new PdfPrinter({
          Helvetica: {
            normal: 'Helvetica',
            bold: 'Helvetica-Bold',
            italics: 'Helvetica-Oblique',
            bolditalics: 'Helvetica-BoldOblique',
          },
        });
        // Lock the file: random owner password discarded → file opens
        // freely but cannot be edited / copied.
        const ownerPassword = crypto.randomBytes(24).toString('base64');
        const pdfDoc = printer.createPdfKitDocument(docDef, {
          ownerPassword,
          permissions: {
            printing: 'highResolution',
            modifying: false,
            copying: false,
            annotating: false,
            fillingForms: false,
            contentAccessibility: true,
            documentAssembly: false,
          },
        });
        const chunks: Buffer[] = [];
        pdfDoc.on('data', (c: Buffer) => chunks.push(c));
        pdfDoc.on('end', () => resolve(Buffer.concat(chunks)));
        pdfDoc.on('error', (err: Error) => reject(err));
        pdfDoc.end();
      } catch (err) {
        this.logger.error('PDF generation failed', err);
        reject(err);
      }
    });
  }

  private watermarkCanvas(width: number, height: number): any[] {
    // Diagonal "SIGN — CONFIDENTIAL" repeated faintly across the page
    return [
      {
        type: 'rect',
        x: 0,
        y: 0,
        w: width,
        h: height,
        color: '#ffffff',
        fillOpacity: 0,
      },
    ];
  }
}

// ─── Tiny helpers ─────────────────────────────────────────

function sectionHeading(text: string) {
  return {
    margin: [0, 18, 0, 8],
    text,
    fontSize: 16,
    bold: true,
    color: BRAND.dark,
  };
}
function paragraph(text: string) {
  return { text, fontSize: 10, color: BRAND.dark, margin: [0, 4, 0, 0] };
}
function bulletPara(text: string) {
  return { text: `• ${text}`, fontSize: 9, margin: [0, 2, 0, 0] };
}
function coverLabel(text: string) {
  return {
    text,
    fontSize: 9,
    color: BRAND.muted,
    bold: true,
    margin: [0, 6, 0, 0],
  };
}
function coverValue(text: string) {
  return { text, fontSize: 11, color: BRAND.dark, margin: [0, 6, 0, 0] };
}
function statBlock(label: string, value: string, color: string) {
  return {
    stack: [
      { text: label, fontSize: 8, color: BRAND.muted, bold: true },
      { text: value, fontSize: 16, color, bold: true, margin: [0, 4, 0, 0] },
    ],
    fillColor: BRAND.light,
    margin: [10, 10, 10, 10],
  };
}
function severityCell(sev: ComplianceFindingSeverity) {
  const color =
    sev === ComplianceFindingSeverity.CRITICAL
      ? BRAND.red
      : sev === ComplianceFindingSeverity.HIGH
      ? BRAND.amber
      : sev === ComplianceFindingSeverity.MEDIUM
      ? '#FFB020'
      : BRAND.muted;
  return { text: sev, fontSize: 8, color, bold: true };
}
function layerTitle(l: ComplianceFindingLayer): string {
  return {
    [ComplianceFindingLayer.STANDARD]: 'Standard Compliance',
    [ComplianceFindingLayer.JURISDICTION]: 'Jurisdiction Compliance',
    [ComplianceFindingLayer.PLAYBOOK]: 'Playbook Compliance',
    [ComplianceFindingLayer.CONFLICT]: 'Cross-Document Conflicts',
  }[l];
}
function statusLabel(s: ObligationStatus): string {
  return s === ObligationStatus.COMPLETED ? 'MET' : s;
}
