import { Link } from 'react-router-dom';
import { Zap } from 'lucide-react';

interface AIDisclaimerProps {
  compact?: boolean;
}

export default function AIDisclaimer({ compact = false }: AIDisclaimerProps) {
  if (compact) {
    return (
      <div className="my-3 border-l-[3px] border-[#7C3AED] bg-[#F5F3FF] px-3 py-2 text-xs italic text-purple-700">
        <Zap size={12} className="mr-1 inline-block" aria-hidden />
        AI-Generated — Not Legal Advice |{' '}
        <Link to="/legal/ai-policy" className="underline">
          View AI Policy
        </Link>
      </div>
    );
  }

  return (
    <div className="my-4 border-l-[3px] border-[#7C3AED] bg-[#F5F3FF] px-4 py-3 text-xs italic text-purple-700">
      <div className="flex items-center gap-1 font-semibold not-italic text-purple-800">
        <Zap size={14} aria-hidden /> AI-Generated Analysis — Not Legal Advice
      </div>
      <p className="mt-1 italic">
        This content was generated by AI and may contain errors or inaccuracies. It must be reviewed
        by a qualified professional before being relied upon.
      </p>
      <Link to="/legal/ai-policy" className="mt-1 inline-block font-medium text-purple-700 underline">
        View AI Policy →
      </Link>
    </div>
  );
}
